import "@/app/globals.css";
import { theme } from "@/app/theme";
import type { Metadata } from "next";

import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
import RecoilProvider from "@/store/Provider";
import { Container } from "@mui/material";
import "@aws-amplify/ui-react/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <RecoilProvider>
        {/* <head /> */}
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body>
            <Container>{children}</Container>
          </body>
        </ThemeProvider>
      </RecoilProvider>
    </html>
  );
}
